"""Shared constants for the Stage 1 experiment."""

DEFAULT_MODEL_NAME = "distilbert-base-uncased"
DEFAULT_MAX_LENGTH = 384
DEFAULT_DOC_STRIDE = 128
DEFAULT_MAX_ANSWER_LENGTH = 30
DEFAULT_N_BEST_SIZE = 20
DEFAULT_VALIDATION_SIZE = 0.1
DEFAULT_SEED = 42

RUN_MODE_BASELINE = "baseline"
RUN_MODE_ABSTAIN = "abstain"
RUN_MODES = (RUN_MODE_BASELINE, RUN_MODE_ABSTAIN)
