"""Shared constants for the Stage 1, Stage 2, and Stage 3 experiments."""

DEFAULT_MODEL_NAME = "distilbert-base-uncased"
DEFAULT_MAX_LENGTH = 384
DEFAULT_DOC_STRIDE = 128
DEFAULT_MAX_ANSWER_LENGTH = 30
DEFAULT_N_BEST_SIZE = 20
DEFAULT_VALIDATION_SIZE = 0.1
DEFAULT_SEED = 42
DEFAULT_SUPPORT_MATCH_F1 = 0.5
DEFAULT_SUPPORT_THRESHOLD_MIN = 0.05
DEFAULT_SUPPORT_THRESHOLD_MAX = 0.95
DEFAULT_SUPPORT_THRESHOLD_STEP = 0.05
DEFAULT_VERIFICATION_NEGATIVES_PER_ANSWERABLE = 1
DEFAULT_VERIFICATION_NEGATIVES_PER_UNANSWERABLE = 1
DEFAULT_CALIBRATION_BINS = 10
DEFAULT_TEMPERATURE_MIN = 0.25
DEFAULT_TEMPERATURE_MAX = 5.0
DEFAULT_TEMPERATURE_STEP = 0.05
DEFAULT_THRESHOLD_GAP_MIN_COUNT = 25

RUN_MODE_BASELINE = "baseline"
RUN_MODE_ABSTAIN = "abstain"
RUN_MODES = (RUN_MODE_BASELINE, RUN_MODE_ABSTAIN)
